### PR TITLE
Fix conditional to include date parameter for geotiff url

### LINKED ISSUE #585: Time / date parameter is missing from 'run analysis'
This issue was discovered for a demo scheduled for Mozambique based off of this PR https://github.com/WFP-VAM/prism-app/pull/572, but I'm assuming this issue is in master.

When I try to run an analysis on SPI for data in February (https://prism-moz.surge.sh/?hazardLayerIds=spi_1m&date=2022-02-21&analysisHazardLayerId=spi_1m&analysisBaselineLayerId=admin_boundaries&analysisDate=2022-02-21&analysisStatistic=mean&analysisThresholdBelow=-1), I get unexpected results (see screenshots below). 

There are clearly many areas where the mean SPI value is less than -1, but only two are returned. When I looked at the request to the API, I see that date is missing from the WCS coverage request so we're getting the latest available data, rather than the time period specified.

Here is the request payload (no date parameter in the geotiff_url):
geojson_out: false
geotiff_url: "https://api.earthobservation.vam.wfp.org/ows/?service=WCS&request=GetCoverage&version=1.0.0&coverage=r1s_dekad&crs=EPSG%3A4326&bbox=30.2%2C-26.9%2C40.8%2C-10.5&width=441&height=681&format=GeoTIFF"
group_by: "source_id"
zones_url: "https://prism-moz.surge.sh/data/mozambique/moz_bnd_adm2_WFP.json"

SPI for the date requested:
Screen Shot 2022-10-10 at 15 49 00

Analysis result:
Screen Shot 2022-10-10 at 15 50 04

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
closes #585 

**How to test:**
- Set to run analysis.
- Select SPI 1 month as hazard layer.
- Select admin boundaries as baseline layer.
- Press run analysis

Verify that within the stats request in the network tab, the geotiff url has the time parameter, with the date specified.

image

### CODE REVIEW

**Comment by wadhwamatic** [comment]
> I'm not so sure this change is correct. Don't we need to fix the root cause which is `disableDateParam` being non-boolean in some code paths?
> 

@JorgeMartinezG - can you please respond and make changes as needed? This fix needs priority. Thanks!

**Comment by JorgeMartinezG** [comment]
> I'm not so sure this change is correct. Don't we need to fix the root cause which is `disableDateParam` being non-boolean in some code paths?
> 
> Image of Graham C **Graham C**
> 
> Was this helpful? [Yes](https://app.pullrequest.com/reviews/ratings/ecc3b5bf-ef13-4126-9357-95d5baa17b9a/true) | [No](https://app.pullrequest.com/reviews/ratings/ecc3b5bf-ef13-4126-9357-95d5baa17b9a/false)
> 
> > _Reviewers will be notified any time you reply to their comments or commit new changes._
> > _You can also request a full follow-up review from your [PullRequest dashboard](https://app.pullrequest.com/dash/projects/1/WFP-VAM/prism-app/reviews/)._

No. disableDateParam is a parameter which is not included in all layers.json files for each country. So, value could be undefined in some cases. For some raster layers time parameter within the wms request is not supported, since the data is not indexed by date/time.

File: src/context/analysisResultStateSlice.ts [hunk 1]
```diff
@@ -246,7 +246,7 @@ const createAPIRequestParams = (
 
   const { wcsConfig } = geotiffLayer;
   const dateValue =
-    !wcsConfig || wcsConfig.disableDateParam === false ? date : undefined;
+    !wcsConfig || !wcsConfig.disableDateParam ? date : undefined;
```
Comment (ericboucher) [inline src/context/analysisResultStateSlice.ts:249]: Could we simplify this as simply:

`!wcsConfig?.disableDateParam` ? date : undefined

Comment (JorgeMartinezG) [reply src/context/analysisResultStateSlice.ts]: included in [8b7d0aa](https://github.com/WFP-VAM/prism-app/pull/586/commits/8b7d0aa5bb44c1223048f3c19d17b3fb24785e86)

**Review by ericboucher — APPROVED** [review]
