### PR TITLE
Point to active layer for geotiff downloads in group layers

### LINKED ISSUE #1003: [Bug]: Downloading a geotiff from the layer menu doesn't correctly grab the selected layer
### What happened?

If I try to download a layer that's part of a group from the layer menu, it grabs the default layer instead of the actively selected layer. The legend area works correctly though.

Steps to reproduce:
1. country=Zimbabwe
2. Load layer: rainfall > global rainfall products > rainfall anomaly 3-month
3. From the layer menu, click the download icon. You'll get a file 'rfq_dekad_YYYY_MM_DD_key'
4. Now try to download from the legend area. You'll get a file 'r3q_dekad_YYYY_MM_DD_key'

The legend area download correctly gets the layer but the layer menu's download gets the default for the group instead.

### Which country / deployment are you running?

Zimbabwe on main

### Add a screenshot (if relevant)

Screenshot 2023-12-02 at 19 13 20

### PR DESCRIPTION
**Pull request by ericboucher**
### Description

This fixes #1003 by pointing to active layer in group layers.

## How to test the feature:

- [ ] change a group wms layer (eg. rainfall agg products and download from the menu
- [ ] download from the legend buttong
- [ ] check that the two resulting files are the same and have the same name
- [ ] check that geotiff downloads of a non-group layer still work as expected

## Checklist - did you ...

Test your changes with

- [ ] `REACT_APP_COUNTRY=rbd yarn start`
- [ ] `REACT_APP_COUNTRY=zimbabwe yarn start`
- [ ] `REACT_APP_COUNTRY=mozambique yarn start`
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

File: frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/LayerDownloadOptions.tsx [hunk 1]
```diff
@@ -35,16 +35,21 @@ import { useSafeTranslation } from 'i18n';
...
 function LayerDownloadOptions({
-  layer,
+  layerId,
   extent,
   selected,
   size,
 }: LayerDownloadOptionsProps) {
   const { t } = useSafeTranslation();
   const dispatch = useDispatch();
+  const layer = useMemo(() => {
```
Comment (echaidemenos) [inline frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/LayerDownloadOptions.tsx:49]: `useMemo` may actually be slowing us down here, since the calculation involved is not that expensive. #901
